### PR TITLE
Add Tornheim_71/Leong_24 signatures

### PR DESCRIPTION
**Pull request by xutao-wang**

### CODE REVIEW

**Comment by Aubreyodom** [comment]
Thank you for this Xutao! I will go through it and pull it in tomorrow! I think I also need to add some info to the annotation table and adjust the list of common names with the info you provided so I'll do that all at once.

**Comment by xutao-wang** [comment]
Thanks Aubrey! Let me know if you need anything about the signature information.

**Comment by Aubreyodom** [comment]
Is there any reason to leave out the 25-gene risk signature identified in the Tornheim paper? I can go ahead and include it as well

**Comment by xutao-wang** [comment]
No, I was focusing on the diagnostic gene list. It is great to add the 25-gene signature, please do so:)

For the 71-gene list, I accidentally included the superscript for genes "MYZAP" and "NRCAM" when copying them from paper into R. Would you also correct that? 

Thank you for your help:)

**Comment by Aubreyodom** [comment]
Cool, I'll include the Tornheim 25 sig as Tornheim_RES_25. And I'll fix those genes as well

**Pull request merged**
